### ISSUE TITLE
Developing a entry point/index for OSM Analytics projects

### ISSUE THREAD

**Issue by brendangatens** [hotosm/osm-analytics#85]
**Goal of the idea**
Create a site that serves as an entry point to OSM analytics tools from various organizations.

[Initial proposal](https://docs.google.com/document/d/1QBUEXh51k2ZYKNbI4TlhmUCEEdd1PVGPx2ZGWMY8kcQ/edit#heading=h.4z87xonac2wm)
[List of tools](https://docs.google.com/spreadsheets/d/1Pk7MCvKkL4FKo2YU5e_u1T00v5_U92wJUeWwlAV5Fj8/edit#gid=0)

**Initial proposed direction**

Considering the intial list of tools has grown, could we give primary treatment (called _Core analytics tools_ below) to the most relevant tools, and give secondary treatment to all other tools?

There has been some discussion on categorizing or tagging tools based on purpose, action, and organization. We discussed having more granular filters on a _Tools_ page.

We're also looking at ways to highlight the organizations and individuals who are contributing to these tools, while finding ways to better call out information on how people (developers) can become contributors, and point out / link to contribution details for individual tools.

Homepage

![osm-analytics-home](https://user-images.githubusercontent.com/1270986/43308243-dbb60a24-9178-11e8-8719-48b9d366e2c0.png)

Menu

![osm-analytics-menu](https://user-images.githubusercontent.com/1270986/43308244-dbdb3812-9178-11e8-9d92-436f9b975d40.png)

Tools page

![osm-analytics-tools](https://user-images.githubusercontent.com/1270986/43308245-dbfa8424-9178-11e8-91b3-31e5e3f60d76.png)

**Comment by awright** [comment]
@brendangatens I think we should/could do an "above the fold" grouping of **Core Projects** and then **Additional Work** following, as second priority. This is exactly how you have it organized here and I wouldn't second guess it?

For this initial MVP, I would put the tools marked as HIGH priority in the [OSMA Ecosystem spreadsheet](https://docs.google.com/spreadsheets/d/1Pk7MCvKkL4FKo2YU5e_u1T00v5_U92wJUeWwlAV5Fj8/edit?usp=sharing) as are the core projects. 

RE: **tagging** -- next week @cgiovando and I  will put together a series of themes. The way I was imaging it, all projects -- core or not -- would have a tag(s). I was thinking of a lot of blog formats, including the Medium screenshot below.

I would like to see a little less real estate to these themes below the core projects (perhaps shorten the height here) and add a section about supporting the work. There are 2 key pieces to that support/involvement-- 1) "join the community" as a developer and/or users and 2) contribute money. 

The first could have a link to the slack channel and a general GitHub and contact email the latter a (perhaps) an email address to keep in touch. I see this as really critical to the ongoing development of these projects. They are sustained by us, but also the community in more ways than one. 

In the initial Language Document I wrote this to support the work. I would recommend we work on this language but it's general point is still valid:
> 
> Roadmap
> All are non-commercial and open software project, and as such there is no formal list of feature requirements required for development. Features and development the Suite team have discussed include…. Etc.  
> Support the Work
> The future direction of OSMA is shaped by the constant flow of code contributions and funding directed towards the implementation of new features. 
> 
> Like OpenStreetMap which it rests upon, OSMA is constantly evolving. It is a community effort built with the commitment of various OpenStreetMap contributors and organizations, the latter including the Humanitarian OpenStreetMap Team <LINK> which serves as a coordinating actor in this work. A full list of supporting organizations can be found below. OSMA was not done alone. 
> 
> If you are interested in supporting the ongoing development of the OSMA Suite of tools including development of the roadmap, please reach out to us directly. <LINK>. 

Note: this was inspired by other OS projects, including [PostGIS](https://postgis.net/support/).  

MEDIUM BLOG TAGGING below
<img width="383" alt="screen shot 2018-07-27 at 8 36 41 am" src="https://user-images.githubusercontent.com/78410/43320972-727b407e-9178-11e8-9171-a64ce8b6939b.png">

Hope this is helpful.

**Comment by willemarcel** [comment]
**Proposal of data store architecture:**

* A YAML file to store the analytic tools
* Another YAML to the OSM tools

The YAML would look like this:

```
projects:
    - name: OpenCities
      url: http://opencities.org
      github: http://github.com/opencities/opencities
      image: images/cities.jpg
      description: |
        Open data today to build resilient and sustainable societies tomorrow. 
      categories:
        - mobility
        - environment
      owners:
        - HOT
        - Someone else
    - name: OSM Analytics for Health
      url: http://osma.hotosm.org
      github: https://github.com/hotosm/osma-health
      description: |
        Extension of OSM Analytics for health campaigns.
      categories:
        - health
      owners:
        - HOT
        - Someone else
```

**Software stack proposal:**
- React
- [Assembly](https://www.mapbox.com/assembly/) (CSS Framework)
